---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Release.Namespace }}-{{ .Chart.Name }}-psp"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
roleRef:
  kind: Role
  name: "{{ .Release.Namespace }}-{{ .Chart.Name }}-psp"
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: "{{ .Release.Namespace }}-{{ .Chart.Name }}"
    