apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
  labels:
    app: {{ .Chart.Name }}-service
    kubernetes.io/name: {{ .Chart.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  selector:
    app: {{ .Chart.Name }}
  # It makes sense to use NodePort type when using with Ingress
  # since we wont be using Ingress, lets try with Loadbalancer
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: http-port
    protocol: TCP