---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Namespace }}-{{ .Chart.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    