# It depends How you want to expose the service
# To get an ingress to work, you might need an ingress controller
# If using AWS try:  Alb Ingress controller
# In this case we will not be using ingress
---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
#   name: {{ .Chart.Name }}
#   namespace: {{ .Release.Namespace }}
#   annotations:
#     kubernetes.io/ingress.class: nginx
# spec:
#   rules:
#   - host: {{ .Values.hostname | quote }}
#     http:
#       paths:
#       - path: /*
#         backend:
#           serviceName: {{ .Chart.Name }}
#           servicePort: http