apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ .Release.Namespace }}-{{ .Chart.Name }}-pdb"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "{{ .Chart.Name }}"
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
