
# ---
# NOTE: Its recommend that you do not Hardcode any kind of credentials, instead directly create secrets with using CRD with or from any kind of vault operators.
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
type: Opaque
data:
  SECRET_ENV: {{ .Values.secret.dummy_2 | b64enc | quote }}
---
# NOTE: there are multiple ways to create and use Docker creds to pull images from private repo
#
#
# apiVersion: v1
# kind: Secret
# metadata:
#   name: {{ .Chart.Name }}-docker-secrets
#   namespace: {{ .Release.Namespace }}
#   labels:
#     app: {{ .Chart.Name }}
#     chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
#     release: "{{ .Release.Name }}"
#     type: kubernetes.io/dockercfg
# data:
#   .dockercfg: {{ "{\"https://xxxx/\":{\"username\":\"xxx\",\"password\":\"xxxx\",\"email\":\"xxx@xxx.xxx\",\"auth\":\"xxx\"}}" | b64enc | quote }}

